backend:
  name: github
  repo: dltt1991/dltt1991.github.io
  branch: main
  auth_type: pkce
  app_id: Ov23licZJDajfQESGJxz

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

locale: zh_Hans

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "标签", name: "tags", widget: "list", default: ["blog"]}
      - {label: "封面图", name: "cover", widget: "image", required: false}
      - {label: "摘要", name: "summary", widget: "text", required: false}
      - {label: "正文", name: "body", widget: "markdown"}

  - name: "pages"
    label: "页面"
    files:
      - label: "关于"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "标题", name: "title", widget: "string"}
          - {label: "正文", name: "body", widget: "markdown"}
